# "org" ensures this Service is used with the correct Serverless Framework Access Key.
org: gallenmar
# "app" enables Serverless Framework Dashboard features and sharing them with other Services.
app: serverless-meter
# "service" is the name of this project. This will also be added to your AWS resource names.
service: serverless-meter

provider:
  name: aws
  runtime: nodejs22.x
  region: eu-central-1
  environment:
    DB_URL: ${env:DB_URL}
    DB_KEY: ${env:DB_KEY}
    STAGE: ${env:STAGE}

functions:
  readId:
    handler: src/read.handler
    events:
      - httpApi:
          path: /counters/{id}
          method: GET
  readAll:
    handler: src/read.handler
    events:
      - httpApi:
          path: /counters
          method: GET
  create:
    handler: src/create.handler
    events:
      - httpApi:
          path: /counters
          method: POST
  update:
    handler: src/update.handler
    events:
      - httpApi:
          path: /counters/{id}
          method: PATCH
  delete:
    handler: src/delete.handler
    events:
      - httpApi:
          path: /counters/{id}
          method: DELETE

plugins:
  - serverless-offline
